<h1>Контакты</h1>
<p>
    icq: 199199538<br/>
    skypeid: vitalyswipe<br/>
    email: vitalyswipe@gmail.com<br/>
    <br/>
    <iframe align="left" src="https://maps.google.ru/maps/place?source=s_q&amp;hl=ru&amp;geocode=&amp;&amp;sll=55.72608,37.64544&amp;sspn=0.127788,0.363579&amp;ie=UTF8&amp;hq=&amp;ll=55.72608,37.64544&amp;spn=0.063897,0.181789&amp;t=m&amp;z=13&amp;output=embed"
            frameborder="0" marginwidth="0" marginheight="0" scrolling="no" align="right" width="600" height="480">
    </iframe>
</p>
<br class="clearfix" />
